// Generated by CoffeeScript 1.8.0
(function() {
  var Scoreboard;

  Scoreboard = React.createClass({
    render: function() {
      return React.createElement("table", {
        "class": "table table-striped"
      }, React.createElement("thead", null, React.createElement("tr", null, React.createElement("th", null, "#"), React.createElement("th", null, "Name"), React.createElement("th", null, "Overall Score"), React.createElement("th", null, "Goal 1"), React.createElement("th", null, "Goal 2"), React.createElement("th", null, "Goal 3"))), React.createElement("tbody", null, React.createElement("tr", null, React.createElement("th", {
        "scope": "row"
      }, "1"), React.createElement("td", null, "Lakeridge 5"), React.createElement("td", null, "91.3"), React.createElement("td", null, "20"), React.createElement("td", null, "11.3"), React.createElement("td", null, "60")), React.createElement("tr", null, React.createElement("th", {
        "scope": "row"
      }, "1"), React.createElement("td", null, "Canyon View"), React.createElement("td", null, "82.3"), React.createElement("td", null, "20"), React.createElement("td", null, "12.3"), React.createElement("td", null, "50")), React.createElement("tr", null, React.createElement("th", {
        "scope": "row"
      }, "1"), React.createElement("td", null, "Mountain View"), React.createElement("td", null, "71"), React.createElement("td", null, "10"), React.createElement("td", null, "21"), React.createElement("td", null, "40"))));
    }
  });

  React.render(React.createElement(Scoreboard, null), document.getElementById('scoreboard'));

}).call(this);
